QA_ITEM_FAMILY( qa_atInBinTree, (), () );
QA_ITEM_FAMILY( qa_atInBinTreeMultimap, (), () );
QA_ITEM( qa_atInBinTree, (), qaResult::PASS_OR_FAIL );
QA_ITEM( qa_atInBinTreeMultimap, (), qaResult::PASS_OR_FAIL );
QA_ITEM_FAMILY( atSafeContainerQA, (), () );
QA_ITEM( atSafeContainerQA, (), qaResult::PASS_OR_FAIL );
QA_ITEM_FAMILY( qa_Delegate, (), () );
QA_ITEM_FAMILY( qa_Delegator, (), () );
QA_ITEM( qa_Delegate, (), qaResult::PASS_OR_FAIL );
QA_ITEM( qa_Delegator, (), qaResult::PASS_OR_FAIL );
QA_ITEM_FAMILY( qa_IList, (), () );
QA_ITEM( qa_IList, (), qaResult::PASS_OR_FAIL );
QA_ITEM_FAMILY( qa_IMap, (), () );
QA_ITEM( qa_IMap, (), qaResult::PASS_OR_FAIL );
QA_ITEM_FAMILY( qa_atInUnionFindManual, (), () );
QA_ITEM_FAST( qa_atInUnionFindManual, (), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAMILY( qa_atInUnionFindAuto, (int setSize, int randomUnions), (setSize, randomUnions) );
QA_ITEM_FAST( qa_atInUnionFindAuto, (10, 5), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAST( qa_atInUnionFindAuto, (10, 10), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAST( qa_atInUnionFindAuto, (10, 20), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAST( qa_atInUnionFindAuto, (100, 50), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAST( qa_atInUnionFindAuto, (100, 100), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAST( qa_atInUnionFindAuto, (100, 200), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAST( qa_atInUnionFindAuto, (1000, 500), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM( qa_atInUnionFindAuto, (1000, 1000), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM( qa_atInUnionFindAuto, (1000, 2000), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM( qa_atInUnionFindAuto, (100000, 50000), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM( qa_atInUnionFindAuto, (100000, 100000), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM( qa_atInUnionFindAuto, (100000, 200000), qaResult::FAIL_OR_TOTAL_TIME );
QA_ITEM_FAMILY(atMapQa, (int runSize), (runSize));
QA_ITEM(atMapQa, (100), qaResult::FAIL_OR_TOTAL_TIME);
QA_ITEM(atMapQa, (1000), qaResult::FAIL_OR_TOTAL_TIME);
QA_ITEM(atMapQa, (10000), qaResult::FAIL_OR_TOTAL_TIME);
