// 
// phcore/channel.h 
// 
// Copyright (C) 1999-2008 Rockstar Games.  All Rights Reserved. 
// 
// Generated by makechannel.bat, do not modify. 
// 

#ifndef PHCORE_CHANNEL_H 
#define PHCORE_CHANNEL_H 

#include "diag/channel.h"

RAGE_DECLARE_CHANNEL(Physics)

#define phAssertf(cond,fmt,...)			RAGE_ASSERTF(Physics,cond,fmt,##__VA_ARGS__)
#define phVerifyf(cond,fmt,...)			RAGE_VERIFYF(Physics,cond,fmt,##__VA_ARGS__)
#define phFatalf(fmt,...)					RAGE_FATALF(Physics,fmt,##__VA_ARGS__)
#define phErrorf(fmt,...)					RAGE_ERRORF(Physics,fmt,##__VA_ARGS__)
#define phWarningf(fmt,...)				RAGE_WARNINGF(Physics,fmt,##__VA_ARGS__)
#define phDisplayf(fmt,...)				RAGE_DISPLAYF(Physics,fmt,##__VA_ARGS__)
#define phDebugf1(fmt,...)					RAGE_DEBUGF1(Physics,fmt,##__VA_ARGS__)
#define phDebugf2(fmt,...)					RAGE_DEBUGF2(Physics,fmt,##__VA_ARGS__)
#define phDebugf3(fmt,...)					RAGE_DEBUGF3(Physics,fmt,##__VA_ARGS__)
#define phLogf(severity,fmt,...)			RAGE_LOGF(Physics,fmt,##__VA_ARGS__)
#define phCondLogf(cond,severity,fmt,...)	RAGE_CONDLOGF(cond,Physics,severity,fmt,##__VA_ARGS__)

#endif // PHCORE_CHANNEL_H 
