// 
// physics/forcesolverconfig.h 
// 
// Copyright (C) 1999-2006 Rockstar Games.  All Rights Reserved. 
// 
#ifndef FORCE_SOLVER_CONFIG_H
#define FORCE_SOLVER_CONFIG_H

#define	MAX_ROPE_COLLIDING_BODIES		16
#define	MAX_ROPE_COLLIDING_ARTICULATED	16

#define USE_CENTRE_POINT_FOR_CONTACTS			0
#define USE_CENTRE_POINT_FOR_CONSTRAINTS		0
#define USE_CENTRE_POINT_FOR_ART_CONSTRAINTS	0
#define POSITIVE_DEPTH_ONLY						(1)
#define POSITIVE_DEPTH_ONLY_THRESHOLD			-0.002f

#if POSITIVE_DEPTH_ONLY
#define POSITIVE_DEPTH_ONLY_ONLY(X) X
#else
#define POSITIVE_DEPTH_ONLY_ONLY(X)
#endif

#define ACCUMULATION_SOLVER_MATH 0

#define TURN_CLAMPING 1

#define USE_ELASTICITY_FOR_MOV_AND_MOV 0

#define SOLVER_OPTIMISATIONS_OFF	0

#if SOLVER_OPTIMISATIONS_OFF
#define SOLVER_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define SOLVER_OPTIMISATIONS()
#endif	//SOLVER_OPTIMISATIONS_OFF

#endif // FORCE_SOLVER_CONFIG_H
