// 
// system/epiccommon.cpp
// 
// Copyright (C) 1999-2019 Rockstar Games.  All Rights Reserved. 
// 

#include "file/file_config.h"

#if EPIC_API_SUPPORTED

#include "epiccommon.h"

namespace rage
{

RAGE_DEFINE_SUBCHANNEL(epic, common)
#undef __rage_channel
#define __rage_channel epic_common

//////////////////////////////////////////////////////////////////////////
// sysEpicApi
//////////////////////////////////////////////////////////////////////////
sysEpicApi::sysEpicApi()
{
	Clear();
}

sysEpicApi::~sysEpicApi()
{
	Shutdown();
}

bool sysEpicApi::Init(HMODULE hEpicDll)
{
	rtry
	{
		rverifyall(hEpicDll != NULL);

#define SYS_EPIC_GET_PROC_ADDR_FUNC(funcName) \
		this->##funcName = (sysEpicApi::funcName##Ptr)GetProcAddress(hEpicDll, #funcName); \
		rverify(this->##funcName != NULL, catchall, epicError("Could not map function: %s", #funcName));

		// Retrieve the address of the exported functions from the Epic DLL
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Initialize);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Platform_Create);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_EpicAccountId_ToString);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_EpicAccountId_FromString);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Shutdown);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Platform_Release);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_Token_Release);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_UserInfo_Release);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Platform_Tick);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Platform_GetAuthInterface);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Platform_GetUserInfoInterface);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_Login);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_Logout);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_GetLoggedInAccountsCount);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_GetLoggedInAccountByIndex);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_GetLoginStatus);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_CopyUserAuthToken);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_AddNotifyLoginStatusChanged);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Auth_RemoveNotifyLoginStatusChanged);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_UserInfo_QueryUserInfo);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_UserInfo_CopyUserInfo);

#if !__NO_OUTPUT
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_EResult_ToString);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Logging_SetCallback);
		SYS_EPIC_GET_PROC_ADDR_FUNC(EOS_Logging_SetLogLevel);
#endif

#undef SYS_EPIC_GET_PROC_ADDR_FUNC
		return true;
	}
	rcatchall
	{
		return false;
	}
}

void sysEpicApi::Clear()
{
	EOS_Initialize = NULL;
	EOS_Platform_Create = NULL;
	EOS_EpicAccountId_ToString = NULL;
	EOS_EpicAccountId_FromString = NULL;
	EOS_Shutdown = NULL;
	EOS_Platform_Release = NULL;
	EOS_Auth_Token_Release = NULL;
	EOS_UserInfo_Release = NULL;
	EOS_Platform_Tick = NULL;
	EOS_Platform_GetAuthInterface = NULL;
	EOS_Platform_GetUserInfoInterface = NULL;
	EOS_Auth_Login = NULL;
	EOS_Auth_Logout = NULL;
	EOS_Auth_GetLoggedInAccountsCount = NULL;
	EOS_Auth_GetLoggedInAccountByIndex = NULL;
	EOS_Auth_GetLoginStatus = NULL;
	EOS_Auth_CopyUserAuthToken = NULL;
	EOS_Auth_AddNotifyLoginStatusChanged = NULL;
	EOS_Auth_RemoveNotifyLoginStatusChanged = NULL;
	EOS_UserInfo_QueryUserInfo = NULL;
	EOS_UserInfo_CopyUserInfo = NULL;
#if !__NO_OUTPUT
	EOS_EResult_ToString = NULL;
	EOS_Logging_SetCallback = NULL;
	EOS_Logging_SetLogLevel = NULL;
#endif
}

void sysEpicApi::Shutdown()
{
	Clear();
}

#if !__NO_OUTPUT
const char* EOSLoginStatusToString(const EOS_ELoginStatus status)
{
	switch(status)
	{
	case EOS_ELoginStatus::EOS_LS_NotLoggedIn:
		return "EOS_LS_NotLoggedIn";
	case EOS_ELoginStatus::EOS_LS_UsingLocalProfile:
		return "EOS_LS_UsingLocalProfile";
	case EOS_ELoginStatus::EOS_LS_LoggedIn:
		return "EOS_LS_LoggedIn";
	case EOS_ELoginStatus::__EOS_ELoginStatus_PAD_INT32__: // autogenerated epic enum
		break;
	}

	return "Unknown";
}

#endif // !__NO_OUTPUT
} // namespace rage

#endif // EPIC_API_SUPPORTED
