#ifndef SYSTEM_MEDIA_FOUNDATION_H
#define SYSTEM_MEDIA_FOUNDATION_H

// Setup for allowing the MF tech to work on vista
// THIS MUST COME BEFORE ANY INCLUDE OF THE MEDIA FOUNDATION HEADERS!
#if RSG_PC

#define MF_SDK_VERSION 0x0001  
#define MF_API_VERSION 0x0070 
#define MF_VERSION (MF_SDK_VERSION << 16 | MF_API_VERSION) 

#endif

#endif // SYSTEM_MEDIA_FOUNDATION_H
