Project data

IncludePath[Platform=='Win32'] $(RAGE_DIR)\3rdparty\Arxan\TransformIT\x86\include\
IncludePath[Platform=='x64'] $(RAGE_DIR)\3rdparty\Arxan\TransformIT\x64\include\

Files {
	autoid.cpp
	autoid.h
	datbase.cpp
	base.h
	base64.cpp
	base64.h
	resource.cpp
	resource.h
	callback.cpp
	callback.h
	datserialize.cpp
	growbuffer.h
	growbuffer.cpp
	serialize.h
	struct.cpp
	struct.h
	safestruct.h
	bitbuffer.cpp
	bitbuffer.h
	datcompress.cpp
	compress.h
	qaseritem.cpp
	qaseritem.h
	resourcehelpers.h
	resourceheader.cpp
	resourceheader.h
	datcompressiondata.cpp
	datcompressiondata.h
	bitfield.h
	aes.cpp
	aes.h
	sha1.cpp
	sha1.h
	pbkdf2.cpp
	pbkdf2.h
	datprotect.cpp
	datprotect.h
	marker.cpp
	marker.h
    rson.cpp
    rson.h
	sax.cpp
	sax.h
	certificateverify.cpp
	certificateverify.h
	multi_keys_AESd.c
	multi_keys_AESd.h
	multi_keys_AESo.c
	multi_keys_AESo.h
    TFIT_keys_iAES1.c
    TFIT_keys_iAES1.h
    TFIT_keys_iAES2.c
    TFIT_keys_iAES2.h
}
Custom {
	data.dtx
}
