// 
// grcore/effect_values.h 
// 
// Copyright (C) 1999-2006 Rockstar Games.  All Rights Reserved. 
// 
#ifndef GRCORE_EFFECT_VALUES_H
#define GRCORE_EFFECT_VALUES_H

namespace rage {

namespace grcRSV {	// RenderStateValue

enum {
	// ZENABLE is a bool

	// FILLMODE:
#if __XENON
	FILL_POINT = 0x01, FILL_WIREFRAME = 0x25, FILL_SOLID = 0x00,
#elif __PS3
	FILL_POINT = 0x1B00, FILL_WIREFRAME = 0x1B01, FILL_SOLID = 0x1B02,
#elif __PSP2
	// no fill modes defined, punt
	FILL_POINT = 1, FILL_WIREFRAME = 1, FILL_SOLID = 1,
#elif RSG_ORBIS
	FILL_POINT = 0x00, FILL_WIREFRAME = 0x1, FILL_SOLID = 0x02,
#else
	FILL_POINT = 0x01, FILL_WIREFRAME = 0x2, FILL_SOLID = 0x03,
#endif
	
	// ZWRITEENABLE is a bool
	// ALPHATESTENABLE is a bool
	// SRCBLEND / DESTBLEND:
#if __XENON
	BLEND_ZERO = 0, BLEND_ONE = 1, BLEND_SRCCOLOR = 4, BLEND_INVSRCCOLOR = 5,
	BLEND_SRCALPHA = 6, BLEND_INVSRCALPHA = 7, BLEND_DESTCOLOR = 8, BLEND_INVDESTCOLOR = 9,
	BLEND_DESTALPHA = 10, BLEND_INVDESTALPHA = 11, BLEND_BLENDFACTOR = 12, BLEND_INVBLENDFACTOR = 13,
	BLEND_CONSTANTALPHA = 14, BLEND_INVCONSTANTALPHA = 15,	// Xenon extension
	BLEND_SRCALPHASAT = 16,
#elif __PS3
	BLEND_ZERO = 0, BLEND_ONE = 1, BLEND_SRCCOLOR = 0x0300, BLEND_INVSRCCOLOR = 0x0301,
	BLEND_SRCALPHA = 0x0302, BLEND_INVSRCALPHA = 0x0303, BLEND_DESTCOLOR = 0x0306, BLEND_INVDESTCOLOR = 0x0307,
	BLEND_DESTALPHA = 0x0304, BLEND_INVDESTALPHA = 0x0305,
	BLEND_BLENDFACTOR = 0x8001, BLEND_INVBLENDFACTOR = 0x8002, BLEND_SRCALPHASAT = 0x0308,
	BLEND_CONSTANTALPHA = 0x8003, BLEND_INVCONSTANTALPHA = 0x8004,
#elif __PSP2
	BLEND_ZERO = 0, BLEND_ONE, BLEND_SRCCOLOR, BLEND_INVSRCCOLOR, BLEND_SRCALPHA, BLEND_INVSRCALPHA,
	BLEND_DESTCOLOR, BLEND_INVDESTCOLOR, BLEND_DESTALPHA, BLEND_INVDESTALPHA,
	BLEND_SRCALPHASAT, BLEND_DESTALPHASAT,
#elif RSG_ORBIS
	BLEND_ZERO = 0, BLEND_ONE, BLEND_SRCCOLOR, BLEND_INVSRCCOLOR, BLEND_SRCALPHA, BLEND_INVSRCALPHA,
	BLEND_DESTALPHA, BLEND_INVDESTALPHA, BLEND_DESTCOLOR, BLEND_INVDESTCOLOR,
	BLEND_SRCALPHASAT, BLEND_BLENDFACTOR = 0x0000000d, BLEND_INVBLENDFACTOR, // Others left off for now
#else
	BLEND_ZERO = 1, BLEND_ONE = 2, BLEND_SRCCOLOR = 3, BLEND_INVSRCCOLOR = 4,
	BLEND_SRCALPHA = 5, BLEND_INVSRCALPHA = 6, BLEND_DESTALPHA = 7, BLEND_INVDESTALPHA = 8, 
	BLEND_DESTCOLOR = 9, BLEND_INVDESTCOLOR = 10,
	BLEND_SRCALPHASAT = 11, BLEND_BLENDFACTOR = 14, BLEND_INVBLENDFACTOR = 15,
	// These are DX10+ only:
	BLEND_SRC1COLOR = 16, BLEND_INVSRC1COLOR = 17, BLEND_SRC1ALPHA = 18, BLEND_INVSRC1ALPHA = 19,
#endif

	// CULLMODE:
#if __XENON
	CULL_NONE = 0x0, CULL_CW = 0x2, CULL_CCW = 0x6,
    NONE_FRONTFACE_CCW = 0x0, FRONT_FRONTFACE_CCW = 0x1, BACK_FRONTFACE_CCW = 0x2,
    NONE_FRONTFACE_CW = 0x4, FRONT_FRONTFACE_CW = 0x5, BACK_FRONTFACE_CW = 0x6,
#elif __PS3
	CULL_NONE = 0, CULL_CW = 0x0901, CULL_CCW = 0x0900,
#elif __PSP2 || RSG_ORBIS
	CULL_NONE = 0, CULL_CW = 1, CULL_CCW = 2,
#elif !__RESOURCECOMPILER && (RSG_PC || RSG_DURANGO)
	CULL_NONE = 1, CULL_CW = 3, CULL_CCW = 2,
#else
	CULL_NONE = 1, CULL_CW = 2, CULL_CCW = 3,
#endif
	CULL_FRONT = CULL_CCW, CULL_BACK = CULL_CW,

	// ZFUNC:
#if __XENON || RSG_ORBIS
	CMP_NEVER = 0, CMP_LESS=1, CMP_EQUAL=2, CMP_LESSEQUAL=3, CMP_GREATER=4, CMP_NOTEQUAL=5, CMP_GREATEREQUAL=6, CMP_ALWAYS=7,
#elif __PS3
	CMP_NEVER = 0x0200, CMP_LESS=0x0201, CMP_EQUAL=0x0202, CMP_LESSEQUAL=0x0203, CMP_GREATER=0x0204, CMP_NOTEQUAL=0x0205, CMP_GREATEREQUAL=0x0206, CMP_ALWAYS=0x0207,
#elif __PSP2
	// needs special handling
	// ZFUNC LESS is 0x0040 0000, so shifted 22
	CMP_NEVER = 0, CMP_LESS=1, CMP_EQUAL=2, CMP_LESSEQUAL=3, CMP_GREATER=4, CMP_NOTEQUAL=5, CMP_GREATEREQUAL=6, CMP_ALWAYS=7,
#else
	CMP_NEVER = 1, CMP_LESS = 2, CMP_EQUAL = 3, CMP_LESSEQUAL = 4, CMP_GREATER = 5, CMP_NOTEQUAL = 6, CMP_GREATEREQUAL = 7,	CMP_ALWAYS = 8,
#endif

	// ALPHAREF is 0-255
	// ALPHAFUNC is the same as ZFUNC
	// ALPHABLENDENABLE is a bool
	// STENCILENABLE is a bool
	// STENCILFAIL, STENCILZFAIL, STENCILPASS:
#if __XENON
	STENCILOP_KEEP = 0, STENCILOP_ZERO = 1, STENCILOP_REPLACE = 2, STENCILOP_INCRSAT = 3,
	STENCILOP_DECRSAT = 4, STENCILOP_INVERT = 5, STENCILOP_INCRWRAP = 6, STENCILOP_DECRWRAP = 7,
#elif __PS3
	// Under GL, INCRSAT is just INCR, and INCR is INCR_WRAP -- we use the correct enumerants.
 	STENCILOP_KEEP = 0x1E00, STENCILOP_ZERO = 0, STENCILOP_REPLACE = 0x1E01, STENCILOP_INCRSAT = 0x1E02,
	STENCILOP_DECRSAT = 0x1E03, STENCILOP_INVERT = 0x150A, STENCILOP_INCRWRAP = 0x8507, STENCILOP_DECRWRAP = 0x8508,
#elif __PSP2
	// Under GXM, INCRSAT is just INCR, and INCR is INCR_WRAP -- we use the correct enumerants.
	STENCILOP_KEEP = 0x00000000U, STENCILOP_ZERO = 0x00000001U, STENCILOP_REPLACE = 0x00000002U, STENCILOP_INCRSAT = 0x00000003U,
	STENCILOP_DECRSAT = 0x00000004U, STENCILOP_INVERT = 0x00000005U, STENCILOP_INCRWRAP = 0x00000006U, STENCILOP_DECRWRAP = 0x00000007U,
#elif RSG_ORBIS
	// Note Orbis supports add/sub of an 'opVal', not just incr/decr, but we force opVal to one.
	STENCILOP_KEEP = 0, STENCILOP_ZERO = 1, STENCILOP_REPLACE = 3, STENCILOP_INCRSAT = 5,
	STENCILOP_DECRSAT = 6, STENCILOP_INVERT = 7, STENCILOP_INCRWRAP = 8, STENCILOP_DECRWRAP = 9,
#else
	STENCILOP_KEEP = 1, STENCILOP_ZERO = 2, STENCILOP_REPLACE = 3, STENCILOP_INCRSAT = 4,
	STENCILOP_DECRSAT = 5, STENCILOP_INVERT = 6, STENCILOP_INCRWRAP = 7, STENCILOP_DECRWRAP = 8,
#endif

	// STENCILFUNC is the same as ZFUNC
	// Well, not on PSP2.  It's the CMP_ functions shifted left 25.

	// STENCILREF is 0-255
	// STENCILMASK is a u32
	// STENCILWRITEMASK is a u32
	// COLORWRITEENABLE: (bitmask of the following)
	COLORWRITEENABLE_NONE = 0,
#if __PSP2
	COLORWRITEENABLE_ALPHA = 1, COLORWRITEENABLE_RED = 2, COLORWRITEENABLE_GREEN = 4, COLORWRITEENABLE_BLUE = 8,
	COLORWRITEENABLE_RGB = 14, COLORWRITEENABLE_ALL = 15,
#else	// Verified for RSG_ORBIS too.
	COLORWRITEENABLE_RED = 1, COLORWRITEENABLE_GREEN = 2, COLORWRITEENABLE_BLUE = 4, COLORWRITEENABLE_ALPHA = 8,
	COLORWRITEENABLE_RGB = 7, COLORWRITEENABLE_ALL = 15,
#endif

	// BLENDOP:
#if __XENON || RSG_ORBIS
	BLENDOP_ADD = 0, BLENDOP_SUBTRACT = 1, BLENDOP_MIN = 2, BLENDOP_MAX = 3, BLENDOP_REVSUBTRACT = 4,
#elif __PS3
	BLENDOP_ADD = 0x8006, BLENDOP_SUBTRACT = 0x800A, BLENDOP_MIN = 0x8007, BLENDOP_MAX = 0x8008, BLENDOP_REVSUBTRACT = 0x800B,
#elif __PSP2
	/*BLENDOP_OPAQUE=0*/ BLENDOP_ADD = 1, BLENDOP_SUBTRACT, BLENDOP_REVSUBTRACT, BLENDOP_MIN /*BOGUS*/, BLENDOP_MAX /*BOGUS*/,
#else
	BLENDOP_ADD = 1, BLENDOP_SUBTRACT = 2, BLENDOP_REVSUBTRACT = 3, BLENDOP_MIN = 4, BLENDOP_MAX = 5,
#endif

	// ALPHATOMASKOFFSETS
#if __XENON
	ALPHATOMASKOFFSETS_DITHERED =  0x00000087, ALPHATOMASKOFFSETS_SOLID = 0x000000AA, 
#elif __PS3
	ALPHATOMASKOFFSETS_DITHERED =  0x00000087, ALPHATOMASKOFFSETS_SOLID = 0x000000AA, 
#else
	ALPHATOMASKOFFSETS_DITHERED =  0x00000087, ALPHATOMASKOFFSETS_SOLID = 0x000000AA, 
#endif

};

}	// namespace grcRSV

namespace grcSSV {		// SamplerStateValue

enum {
	// ADDRESSU/V/W:
#if __XENON || RSG_ORBIS
	TADDRESS_WRAP = 0, TADDRESS_MIRROR = 1, TADDRESS_CLAMP = 2, TADDRESS_MIRRORONCE = 3, TADDRESS_BORDER_HALF = 4,
	TADDRESS_MIRRORONCE_BORDER_HALF = 5, TADDRESS_BORDER = 6, TADDRESS_MIRRORONCE_BORDER = 7,
#else
	TADDRESS_WRAP = 1, TADDRESS_MIRROR = 2, TADDRESS_CLAMP = 3, TADDRESS_BORDER = 4, TADDRESS_MIRRORONCE = 5,
#endif

	// BORDERCOLOR is a 32bit color
	// MAGFILTER/MINFILTER/MIPFILTER
#if __XENON
	TEXF_NONE = 2, TEXF_POINT = 0, TEXF_LINEAR = 1, TEXF_ANISOTROPIC = 4,
	TEXF_QUINCUNX = 4, TEXF_GAUSSIAN = 4, TEXF_QUINCUNX_ALT = 4,	// PS3-specific, map to anisotropic on Xenon
#elif RSG_ORBIS
	// These are not directly usable; XY filter modes start at one less.  But this doesn't matter so much now
	// with state blocks.
	TEXF_NONE = 0, TEXF_POINT = 1, TEXF_LINEAR = 2, TEXF_ANISOTROPIC = 3,
	TEXF_QUINCUNX = 4, TEXF_GAUSSIAN = 4, TEXF_QUINCUNX_ALT = 4,	// PS3-specific, map to anisotropic+bilinear on Orbis

#else
	TEXF_NONE = 0, TEXF_POINT = 1, TEXF_LINEAR = 2, TEXF_ANISOTROPIC = 3,
	TEXF_QUINCUNX = 4, TEXF_GAUSSIAN = 5, TEXF_QUINCUNX_ALT = 6,	// PS3-specific
	TEXF_PYRAMIDALQUAD = 6, TEXF_GAUSSIANQUAD = 7,	// PC-specific
#endif

	// MIPMAPLODBIAS is a float
	// MAXMIPLEVEL is a u32
	// MAXANISOTROPY is a u32

#if __XENON
	TRILINEAR_IMMEDIATE = 0, TRILINEAR_ONESIXTH = 1, TRILINEAR_ONEFOURTH = 2, TRILINEAR_THREEEIGHTHS = 3,
#else
	// On PS3 it's a slope value from a table:
	// 1, 1.125, 1.25, 1.375, 1.5, 1.625, 1.75, 1.875, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5,
	// 3.75, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 9, 10, 11, 12, 13, 14, and 15.
	// ONESIXTH implies 2/3 left over, slope = 3/2 = 1.5 (index 4)
	// ONEFOURTH implies 1/2 left over, slope = 2 (index 8)
	// THREEEIGHTHS implies 1/4 left over, slope = 4 (index 16)
	TRILINEAR_IMMEDIATE = 0, TRILINEAR_ONESIXTH = 4, TRILINEAR_ONEFOURTH = 8, TRILINEAR_THREEEIGHTHS = 16,
#endif

	// PS3-specific:
	TEXTUREZFUNC_NEVER	= (0), TEXTUREZFUNC_LESS = (1), TEXTUREZFUNC_EQUAL = (2), TEXTUREZFUNC_LEQUAL = (3),
	TEXTUREZFUNC_GREATER = (4), TEXTUREZFUNC_NOTEQUAL = (5), TEXTUREZFUNC_GEQUAL	= (6), TEXTUREZFUNC_ALWAYS	= (7),

	// DX10-specific for now.  (Other platforms will remap via LUT)
	// Example: MIN_LINEAR_MAG_MIP_POINT means "minification is linear, magnification and mip are point (nearest).
	FILTER_MIN_MAG_MIP_POINT = 0,
	FILTER_MIN_MAG_POINT_MIP_LINEAR = 0x1,
	FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x4,
	FILTER_MIN_POINT_MAG_MIP_LINEAR = 0x5,
	FILTER_MIN_LINEAR_MAG_MIP_POINT = 0x10,
	FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x11,
	FILTER_MIN_MAG_LINEAR_MIP_POINT = 0x14,
	FILTER_MIN_MAG_MIP_LINEAR = 0x15,
	FILTER_ANISOTROPIC = 0x55,
#if __PS3
	FILTER_GAUSSIAN = 0x65,			// PS3 extension
#else
	FILTER_GAUSSIAN = 0x55,			// Same as anisotropic on other platforms
#endif

#if RSG_PC || RSG_DURANGO || RSG_ORBIS // These are generally not what you wanted on DX9 platforms.
	FILTER_COMPARISON_MIN_MAG_MIP_POINT = 0x80,
	FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR = 0x81,
	FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x84,
	FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR = 0x85,
	FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT = 0x90,
	FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x91,
	FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT = 0x94,
	FILTER_COMPARISON_MIN_MAG_MIP_LINEAR = 0x95,
	FILTER_COMPARISON_ANISOTROPIC = 0xd5,
#endif
};

}	// namespace grcSSV

}	// namespace rage

#endif
