//
// grcore/texturedebugflags.h
//
// Copyright (C) 2013 Rockstar Games.  All Rights Reserved.
//

#ifndef GRCORE_TEXTUREDEBUGFLAGS_H
#define GRCORE_TEXTUREDEBUGFLAGS_H

#if defined(ASSET_ANALYSIS_TOOL)
#include "../../../../tools/common/common.h"
#include <string>
#elif __BANK
#include <string>
#endif // __BANK

namespace rage {

enum eTextureConversionFlags
{
	TEXTURE_CONVERSION_FLAG_PROCESSED         = 0x80,
	TEXTURE_CONVERSION_FLAG_SKIPPED           = 0x40,
	TEXTURE_CONVERSION_FLAG_FAILED_PROCESSING = 0x20,
	TEXTURE_CONVERSION_FLAG_INVALID_METADATA  = 0x10, // still gets processed, using default templates
	TEXTURE_CONVERSION_FLAG_OPTIMISED_DXT     = 0x08, // DXT format was inefficient so texture has been optimised
	TEXTURE_CONVERSION_FLAG_NO_PROCESSING     = TEXTURE_CONVERSION_FLAG_SKIPPED | TEXTURE_CONVERSION_FLAG_FAILED_PROCESSING,
	TEXTURE_CONVERSION_FLAG_MASK              = 0xf8,
};

enum eTextureTemplateType
{
	TEXTURE_TEMPLATE_TYPE_UNKNOWN = 0       ,
	TEXTURE_TEMPLATE_TYPE_DEFAULT           ,
	TEXTURE_TEMPLATE_TYPE_TERRAIN           ,
	TEXTURE_TEMPLATE_TYPE_CLOUDDENSITY      ,
	TEXTURE_TEMPLATE_TYPE_CLOUDNORMAL       ,
	TEXTURE_TEMPLATE_TYPE_CABLE             ,
	TEXTURE_TEMPLATE_TYPE_FENCE             ,
	TEXTURE_TEMPLATE_TYPE_ENVEFF            ,
	TEXTURE_TEMPLATE_TYPE_SCRIPT            ,
	TEXTURE_TEMPLATE_TYPE_WATERFLOW         ,
	TEXTURE_TEMPLATE_TYPE_WATERFOAM         ,
	TEXTURE_TEMPLATE_TYPE_WATERFOG          ,
	TEXTURE_TEMPLATE_TYPE_WATEROCEAN        ,
	TEXTURE_TEMPLATE_TYPE_WATER             ,
	TEXTURE_TEMPLATE_TYPE_FOAMOPACITY       ,
	TEXTURE_TEMPLATE_TYPE_FOAM              ,
	TEXTURE_TEMPLATE_TYPE_DIFFUSEMIPSHARPEN ,
	TEXTURE_TEMPLATE_TYPE_DIFFUSEDETAIL     ,
	TEXTURE_TEMPLATE_TYPE_DIFFUSEDARK       ,
	TEXTURE_TEMPLATE_TYPE_DIFFUSEALPHAOPAQUE,
	TEXTURE_TEMPLATE_TYPE_DIFFUSE           ,
	TEXTURE_TEMPLATE_TYPE_DETAIL            ,
	TEXTURE_TEMPLATE_TYPE_NORMAL            ,
	TEXTURE_TEMPLATE_TYPE_SPECULAR          ,
	TEXTURE_TEMPLATE_TYPE_EMISSIVE          ,
	TEXTURE_TEMPLATE_TYPE_TINTPALETTE       ,
	TEXTURE_TEMPLATE_TYPE_SKIPPROCESSING    ,
	TEXTURE_TEMPLATE_TYPE_DONOTOPTIMIZE     ,
	TEXTURE_TEMPLATE_TYPE_TEST              ,
	TEXTURE_TEMPLATE_TYPE_COUNT             ,
	TEXTURE_TEMPLATE_TYPE_MASK              = 0x01f, // 5 bits (up to 32 template types)

	TEXTURE_TEMPLATE_TYPE_FLAG_NOT_HALF     = 0x020, // 4 bits
	TEXTURE_TEMPLATE_TYPE_FLAG_HD_SPLIT     = 0x040,
	TEXTURE_TEMPLATE_TYPE_FLAG_FULL         = 0x080,
	TEXTURE_TEMPLATE_TYPE_FLAG_MAPS_HALF    = 0x100,
	TEXTURE_TEMPLATE_TYPE_FLAG_MASK         = 0x1e0,

	TEXTURE_TEMPLATE_TYPE_VERSION_MASK      = 0xe00, // 3 bits
	TEXTURE_TEMPLATE_TYPE_VERSION_SHIFT     = 9,
	TEXTURE_TEMPLATE_TYPE_VERSION_CURRENT   = 1 << TEXTURE_TEMPLATE_TYPE_VERSION_SHIFT,
};
CompileTimeAssert(TEXTURE_TEMPLATE_TYPE_COUNT <= TEXTURE_TEMPLATE_TYPE_MASK + 1);

#if __BANK || defined(ASSET_ANALYSIS_TOOL)
// note -- these functions must return std::string because they are used in my external tool
std::string GetTextureConversionFlagsString(u8 flags);
std::string GetTextureTemplateTypeString(u16 templateType);
#endif // __BANK || defined(ASSET_ANALYSIS_TOOL)

} // namespace rage

#endif // GRCORE_TEXTUREDEBUGFLAGS_H
