// 
// grcore/translate_state.h
// 
// Copyright (C) 1999-2006 Rockstar Games.  All Rights Reserved. 
// 

static D3DRENDERSTATETYPE TranslateRenderState[] = {
	D3DRS_ZENABLE,
	D3DRS_FILLMODE,
	D3DRS_ZWRITEENABLE,
	D3DRS_ALPHATESTENABLE,
	D3DRS_SRCBLEND,
	D3DRS_DESTBLEND,
	D3DRS_CULLMODE,
	D3DRS_ZFUNC,
	D3DRS_ALPHAREF,
	D3DRS_ALPHAFUNC,
	D3DRS_ALPHABLENDENABLE,
	D3DRS_STENCILENABLE,
	D3DRS_STENCILFAIL,
	D3DRS_STENCILZFAIL,
	D3DRS_STENCILPASS,
	D3DRS_STENCILFUNC,
	D3DRS_STENCILREF,
	D3DRS_STENCILMASK,
	D3DRS_STENCILWRITEMASK,
	D3DRS_COLORWRITEENABLE,
	D3DRS_BLENDOP,
};

static D3DSAMPLERSTATETYPE TranslateSamplerState[] = {
	D3DSAMP_ADDRESSU,
	D3DSAMP_ADDRESSV,
	D3DSAMP_ADDRESSW,
	D3DSAMP_BORDERCOLOR,
	D3DSAMP_MAGFILTER,
	D3DSAMP_MINFILTER,
	D3DSAMP_MIPFILTER,
	D3DSAMP_MIPMAPLODBIAS,
	D3DSAMP_MAXMIPLEVEL,
	D3DSAMP_MAXANISOTROPY,
#if __WIN32PC
	D3DSAMP_SRGBTEXTURE,
#endif
};
