#--------------------------------------------------------------------------------------------------
# Generated by SPA (Version 1.4.7 build 3  -  Built with MSC 14.0)
# Copyright (C) 2007-2010 Sony Computer Entertainment Inc. All Rights Reserved.
#--------------------------------------------------------------------------------------------------


    .section .text,"ax"
    .align 4 # overall alignment for this section


    .align 3

#--------------------------------------------------------------------------------------------------
# Function: warpTransformLoop
#--------------------------------------------------------------------------------------------------
    .global warpTransformLoop
    .type warpTransformLoop@function
warpTransformLoop:
_local_c0de000000000000:
                                                           stqd        $81,-32($1)
                                                           stqd        $80,-16($1)
    nop         ;
_local_c0db000000000000:
                                                           brz         $5,_local_c0de000000000003
    ai          $2,$3,64;                   /* +2 */       lqr         $27,il128_constant_04_05_06_07_14_15_16_17_00_01_02_03_10_11_12_13
                                                           lqr         $26,il128_constant_00_01_02_03_10_11_12_13_04_05_06_07_14_15_16_17
                                                           lqd         $49,-32($2)
                                                           lqd         $51,-48($2)
                                                           lqd         $50,-16($2)
                                                           lqd         $52,-64($2)
                                                           lqr         $25,il128_constant_18_19_1a_1b_1c_1d_1e_1f_00_01_02_03_04_05_06_07
                                                           lqr         $38,il128_constant_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f
                                                           lqr         $60,il128_constant_00_01_02_03_00_01_02_03_00_01_02_03_00_01_02_03
                                                           lqr         $24,il128_constant_00_01_02_03_04_05_06_07_18_19_1a_1b_1c_1d_1e_1f
                                                           shufb       $53,$49,$50,$27
                                                           shufb       $54,$52,$51,$26
                                                           lqr         $58,il128_constant_04_05_06_07_04_05_06_07_04_05_06_07_04_05_06_07
                                                           shufb       $23,$6,$6,$38
                                                           shufb       $22,$6,$6,$60
                                                           shufb       $80,$54,$53,$24
                                                           lqr         $21,il128_constant_08_09_0a_0b_18_19_1a_1b_08_09_0a_0b_18_19_1a_1b
                                                           lqr         $73,il128_constant_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b
                                                           shufb       $20,$7,$7,$38
    fma         $48,$80,$22,$23;                           shufb       $19,$6,$6,$58
                                                           shufb       $28,$7,$7,$60
                                                           shufb       $74,$53,$54,$25
                                                           shufb       $47,$52,$51,$21
                                                           shufb       $46,$49,$50,$21
    fma         $45,$80,$28,$20;                           lnop        
    fma         $44,$74,$19,$48;                           shufb       $29,$6,$6,$73
                                                           shufb       $30,$7,$7,$58
                                                           shufb       $53,$47,$46,$24
    fma         $43,$74,$30,$45;                           lnop        
    fma         $42,$53,$29,$44;                           shufb       $31,$7,$7,$73
                                                           shufb       $32,$15,$15,$60
    fm          $34,$16,$18;
    fma         $41,$53,$31,$43;                           lnop        
    fm          $81,$42,$32;                               shufb       $33,$15,$15,$58
    fm          $36,$17,$18;
    ilhu        $35,16256;
    ai          $6,$2,64;                   /* +1 */
    fm          $59,$41,$33;
    fma         $40,$81,$34,$35;            /* +1 */       lqd         $64,-32($6)
                                                           lqd         $68,-48($6)
                                                           lqd         $63,-16($6)
                                                           lqd         $69,-64($6)
    fma         $47,$59,$36,$40;            /* +1 */       shufb       $71,$64,$63,$27
                                                           shufb       $72,$69,$68,$26
                                                           frest       $39,$47                     /* +1 */
                                                           shufb       $49,$72,$71,$24
    fi          $66,$47,$39;                /* +1 */       shufb       $44,$8,$8,$38
                                                           shufb       $43,$8,$8,$60
    fma         $61,$49,$22,$23;                           shufb       $54,$71,$72,$25
                                                           lnop        
    fma         $77,$80,$43,$44;            /* +1 */       shufb       $57,$69,$68,$21
    nop         ;                                          shufb       $75,$64,$63,$21
    fnms        $67,$66,$47,$35;            /* +1 */       shufb       $39,$8,$8,$58
    fma         $9,$54,$19,$61;                            lnop        
    fma         $62,$49,$28,$20;                           shufb       $57,$57,$75,$24
    fma         $65,$74,$39,$77;            /* +1 */       lnop        
    ori         $3,$2,0;                                   lqr         $37,il128_constant_00_01_12_13_04_05_16_17_08_09_1a_1b_0c_0d_1e_1f
    fma         $80,$67,$66,$66;            /* +1 */       shufb       $52,$8,$8,$73
    fma         $70,$57,$29,$9;                            lqr         $55,il128_constant_80_00_00_00_80_00_00_00_80_00_00_00_80_00_00_00
    ori         $7,$6,0;                                   shufb       $56,$15,$15,$73
    fma         $16,$54,$30,$62;                           lqr         $51,il128_constant_00_01_02_03_04_05_06_07_13_80_80_80_0c_0d_0e_0f
    fma         $17,$53,$52,$65;            /* +1 */       lqr         $69,il128_constant_08_09_0a_0b_18_19_1a_1b_00_01_02_03_10_11_12_13
    ila         $38,0;                                     lqr         $68,il128_constant_04_05_06_07_14_15_16_17_0c_0d_0e_0f_1c_1d_1e_1f
    fm          $2,$81,$80;                 /* +1 */       shufb       $64,$11,$11,$58
    fm          $70,$70,$32;                               shufb       $63,$10,$10,$58
    and         $71,$47,$55;                /* +1 */       lqr         $67,il128_constant_08_09_0a_0b_18_19_1a_1b_0c_0d_0e_0f_1c_1d_1e_1f
    fma         $74,$57,$31,$16;                           shufb       $65,$10,$10,$60
    fm          $75,$17,$56;                /* +1 */       shufb       $66,$11,$11,$60
    fm          $72,$59,$80;                /* +1 */       lqr         $48,il128_constant_0a_0b_02_03_06_07_12_13_16_17_1a_1b_80_80_80_80
    xor         $78,$2,$71;                 /* +1 */       lqr         $42,il128_constant_0c_0d_0e_0f_1c_1d_1e_1f_08_09_0a_0b_18_19_1a_1b
    ai          $8,$6,64;                                  shufb       $60,$81,$59,$26             /* +1 */
    fma         $62,$78,$65,$66;            /* +1 */       shufb       $61,$81,$59,$67             /* +1 */
    fm          $59,$74,$33;                               lqr         $40,il128_constant_08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_14_15_16_17
    fcgt        $76,$75,$38;                /* +1 */       lqr         $58,il128_constant_00_01_02_03_10_11_12_13_08_09_0a_0b_18_19_1a_1b
    xor         $77,$72,$71;                /* +1 */       shufb       $16,$10,$10,$73
    selb        $76,$38,$75,$76;            /* +1 */       lqr         $53,il128_constant_0c_0d_0e_0f_1c_1d_1e_1f_04_05_06_07_14_15_16_17
    fma         $72,$77,$63,$64;            /* +1 */       shufb       $71,$11,$11,$73
    cflts       $74,$62,3;                  /* +1 */       shufb       $15,$76,$47,$27             /* +1 */
#--------------------------------------------------------------------------------------------------
# SOFTWARE PIPELINING FEEDBACK 
#--------------------------------------------------------------------------------------------------
# 
# Loop stats - warpTransformLoop::Loop
# (ims enabled, sms disabled, optimisation level 2)
#        resmii : 51 (*)         (resource constrained)
#        recmii : 2              (recurrence constrained)
# resource usage:
#        even pipe : 48 inst. (94% use)
#                      SP[25] FX[20] FI[3] 
#        odd pipe  : 51 inst. (100% use) (*)
#                      SH[38] LS[12] BR[1] 
# misc:
#        linear schedule = 142 cycles (for information only)
# software pipelining:
#        best pipelined schedule = 53 cycles (pipelined, 4 iterations in parallel)
# software pipelining adjustments:
#        collapsed 3/3 epilogs (removed 233 instructions)
#        not generating non-pipelined loop since trip count >=1 (1)
# estimated loop performance:
#        =53*n+113 cycles
# 
#--------------------------------------------------------------------------------------------------
    .align 3
_local_c0de000000000002:
    nop         ;                                          shufb       $78,$60,$15,$24             /* +3 */
    fma         $73,$70,$34,$35;            /* +2 */       lqd         $11,-16($8)                 /* +1 */
    cflts       $77,$72,3;                  /* +3 */       lqd         $10,-64($8)                 /* +1 */
    fcgt        $17,$47,$38;                /* +3 */       lqd         $6,-48($8)                  /* +1 */
    fm          $75,$76,$80;                /* +3 */       lqd         $2,-32($8)                  /* +1 */
    nop         ;                                          stqd        $78,-64($3)                 /* +3 */
    and         $18,$74,$14;                /* +3 */       shufb       $81,$76,$47,$42             /* +3 */
    fma         $47,$59,$36,$73;            /* +2 */       hbrr        _local_c0db000000000002,_local_c0de000000000002
    fma         $73,$49,$45,$46;            /* +2 */       shlqbyi     $18,$18,2                   /* +3 */
    and         $74,$77,$14;                /* +3 */       shufb       $80,$10,$6,$26              /* +1 */
    fma         $79,$49,$43,$44;            /* +2 */       shufb       $78,$2,$11,$27              /* +1 */
    fma         $77,$75,$16,$71;            /* +3 */       lnop        
    ori         $9,$3,0;                    /* +3 */       shufb       $76,$18,$74,$37             /* +3 */
    ori         $3,$7,0;                    /* +2 */       frest       $75,$47                     /* +2 */
    fma         $74,$54,$41,$73;            /* +2 */       shufb       $49,$80,$78,$24             /* +1 */
    ori         $7,$8,0;                    /* +1 */       shufb       $73,$62,$72,$58             /* +3 */
    selb        $18,$76,$17,$55;            /* +3 */       shufb       $76,$2,$11,$21              /* +1 */
    fma         $79,$54,$39,$79;            /* +2 */       shufb       $2,$62,$72,$68              /* +3 */
    fi          $17,$47,$75;                /* +2 */       shufb       $11,$77,$18,$69             /* +3 */
    ai          $4,$4,64;                   /* +3 */       shufb       $62,$77,$18,$53             /* +3 */
    fma         $18,$49,$28,$20;            /* +1 */       shufb       $54,$78,$80,$25             /* +1 */
    fma         $72,$49,$22,$23;            /* +1 */       shufb       $75,$10,$6,$21              /* +1 */
    ai          $8,$8,64;                                  shufb       $77,$11,$73,$25             /* +3 */
    fma         $78,$57,$52,$79;            /* +2 */       shufb       $79,$62,$2,$25              /* +3 */
    fma         $74,$57,$50,$74;            /* +2 */       shufb       $6,$73,$11,$24              /* +3 */
    fnms        $10,$17,$47,$35;            /* +2 */       shufb       $11,$2,$62,$24              /* +3 */
    fcgt        $62,$12,$77;                /* +3 */       shufb       $57,$75,$76,$24             /* +1 */
    fcgt        $73,$12,$79;                /* +3 */       shufb       $75,$60,$15,$40             /* +3 */
    fcgt        $80,$79,$13;                /* +3 */       shufb       $74,$61,$81,$24             /* +3 */
    fcgt        $76,$77,$13;                /* +3 */       shufb       $81,$61,$81,$40             /* +3 */
    fma         $2,$54,$19,$72;             /* +1 */       shufb       $15,$73,$80,$48             /* +3 */
    fma         $80,$10,$17,$17;            /* +2 */       shufb       $76,$62,$76,$48             /* +3 */
    fcgt        $10,$6,$13;                 /* +3 */       stqd        $75,-48($9)                 /* +3 */
    fcgt        $17,$12,$6;                 /* +3 */       stqd        $81,-16($9)                 /* +3 */
    fma         $61,$54,$30,$18;            /* +1 */       shufb       $60,$70,$59,$26             /* +2 */
    fcgt        $18,$11,$13;                /* +3 */       shufb       $62,$17,$10,$48             /* +3 */
    fcgt        $72,$12,$11;                /* +3 */       gbh         $73,$76                     /* +3 */
    fm          $75,$70,$80;                /* +2 */       stqd        $74,-32($9)                 /* +3 */
    fm          $78,$78,$56;                /* +2 */       shufb       $9,$72,$18,$48              /* +3 */
    fm          $10,$59,$80;                /* +2 */       gbh         $15,$15                     /* +3 */
    fma         $81,$57,$29,$2;             /* +1 */       shufb       $74,$77,$73,$51             /* +3 */
    and         $76,$47,$55;                /* +2 */       gbh         $77,$62                     /* +3 */
    fma         $17,$57,$31,$61;            /* +1 */       gbh         $2,$9                       /* +3 */
    xor         $18,$75,$76;                /* +2 */       shufb       $9,$79,$15,$51              /* +3 */
    fcgt        $61,$78,$38;                /* +2 */       stqd        $74,-32($4)                 /* +3 */
    xor         $72,$10,$76;                /* +2 */       shufb       $73,$6,$77,$51              /* +3 */
    fma         $62,$18,$65,$66;            /* +2 */       shufb       $79,$11,$2,$51              /* +3 */
    selb        $76,$38,$78,$61;            /* +2 */       shufb       $61,$70,$59,$67             /* +2 */
    fm          $70,$81,$32;                /* +1 */       stqd        $9,-16($4)                  /* +3 */
    fma         $72,$72,$63,$64;            /* +2 */       shufb       $15,$76,$47,$27             /* +2 */
    ai          $5,$5,-1;                   /* +3 */       stqd        $73,-64($4)                 /* +3 */
    fm          $59,$17,$33;                /* +1 */       stqd        $79,-48($4)                 /* +3 */
    cflts       $74,$62,3;                  /* +2 */
_local_c0db000000000002:
                                                           brnz        $5,_local_c0de000000000002  /* +3 */
    .align 3
_local_c0de000000000003:
                                                           lqd         $80,-16($1)
                                                           lqd         $81,-32($1)
_local_c0db000000000003:
                                                           bi          $0
    .size warpTransformLoop, .-warpTransformLoop

    .section .gnu.linkonce.r.80_80_00_01_80_80_02_03_80_80_14_15_80_80_16_17,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_80_80_00_01_80_80_02_03_80_80_14_15_80_80_16_17
il128_constant_80_80_00_01_80_80_02_03_80_80_14_15_80_80_16_17:
    .byte	0x80, 0x80, 0x00, 0x01, 0x80, 0x80, 0x02, 0x03, 0x80, 0x80, 0x14, 0x15, 0x80, 0x80, 0x16, 0x17

    .section .gnu.linkonce.r.80_00_00_00_80_00_00_00_80_00_00_00_80_00_00_00,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_80_00_00_00_80_00_00_00_80_00_00_00_80_00_00_00
il128_constant_80_00_00_00_80_00_00_00_80_00_00_00_80_00_00_00:
    .byte	0x80, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00

    .section .gnu.linkonce.r.18_19_1a_1b_1c_1d_1e_1f_00_01_02_03_04_05_06_07,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_18_19_1a_1b_1c_1d_1e_1f_00_01_02_03_04_05_06_07
il128_constant_18_19_1a_1b_1c_1d_1e_1f_00_01_02_03_04_05_06_07:
    .byte	0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07

    .section .gnu.linkonce.r.0c_0d_0e_0f_1c_1d_1e_1f_08_09_0a_0b_18_19_1a_1b,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_0c_0d_0e_0f_1c_1d_1e_1f_08_09_0a_0b_18_19_1a_1b
il128_constant_0c_0d_0e_0f_1c_1d_1e_1f_08_09_0a_0b_18_19_1a_1b:
    .byte	0x0c, 0x0d, 0x0e, 0x0f, 0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x09, 0x0a, 0x0b, 0x18, 0x19, 0x1a, 0x1b

    .section .gnu.linkonce.r.0c_0d_0e_0f_1c_1d_1e_1f_04_05_06_07_14_15_16_17,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_0c_0d_0e_0f_1c_1d_1e_1f_04_05_06_07_14_15_16_17
il128_constant_0c_0d_0e_0f_1c_1d_1e_1f_04_05_06_07_14_15_16_17:
    .byte	0x0c, 0x0d, 0x0e, 0x0f, 0x1c, 0x1d, 0x1e, 0x1f, 0x04, 0x05, 0x06, 0x07, 0x14, 0x15, 0x16, 0x17

    .section .gnu.linkonce.r.0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f
il128_constant_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f_0c_0d_0e_0f:
    .byte	0x0c, 0x0d, 0x0e, 0x0f, 0x0c, 0x0d, 0x0e, 0x0f, 0x0c, 0x0d, 0x0e, 0x0f, 0x0c, 0x0d, 0x0e, 0x0f

    .section .gnu.linkonce.r.0a_0b_02_03_06_07_12_13_16_17_1a_1b_80_80_80_80,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_0a_0b_02_03_06_07_12_13_16_17_1a_1b_80_80_80_80
il128_constant_0a_0b_02_03_06_07_12_13_16_17_1a_1b_80_80_80_80:
    .byte	0x0a, 0x0b, 0x02, 0x03, 0x06, 0x07, 0x12, 0x13, 0x16, 0x17, 0x1a, 0x1b, 0x80, 0x80, 0x80, 0x80

    .section .gnu.linkonce.r.08_09_0a_0b_18_19_1a_1b_0c_0d_0e_0f_1c_1d_1e_1f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_08_09_0a_0b_18_19_1a_1b_0c_0d_0e_0f_1c_1d_1e_1f
il128_constant_08_09_0a_0b_18_19_1a_1b_0c_0d_0e_0f_1c_1d_1e_1f:
    .byte	0x08, 0x09, 0x0a, 0x0b, 0x18, 0x19, 0x1a, 0x1b, 0x0c, 0x0d, 0x0e, 0x0f, 0x1c, 0x1d, 0x1e, 0x1f

    .section .gnu.linkonce.r.08_09_0a_0b_18_19_1a_1b_08_09_0a_0b_18_19_1a_1b,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_08_09_0a_0b_18_19_1a_1b_08_09_0a_0b_18_19_1a_1b
il128_constant_08_09_0a_0b_18_19_1a_1b_08_09_0a_0b_18_19_1a_1b:
    .byte	0x08, 0x09, 0x0a, 0x0b, 0x18, 0x19, 0x1a, 0x1b, 0x08, 0x09, 0x0a, 0x0b, 0x18, 0x19, 0x1a, 0x1b

    .section .gnu.linkonce.r.08_09_0a_0b_18_19_1a_1b_00_01_02_03_10_11_12_13,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_08_09_0a_0b_18_19_1a_1b_00_01_02_03_10_11_12_13
il128_constant_08_09_0a_0b_18_19_1a_1b_00_01_02_03_10_11_12_13:
    .byte	0x08, 0x09, 0x0a, 0x0b, 0x18, 0x19, 0x1a, 0x1b, 0x00, 0x01, 0x02, 0x03, 0x10, 0x11, 0x12, 0x13

    .section .gnu.linkonce.r.08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_80_80_80_80,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_80_80_80_80
il128_constant_08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_80_80_80_80:
    .byte	0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x80, 0x80, 0x80, 0x80

    .section .gnu.linkonce.r.08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_14_15_16_17,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_14_15_16_17
il128_constant_08_09_0a_0b_0c_0d_0e_0f_10_11_12_13_14_15_16_17:
    .byte	0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17

    .section .gnu.linkonce.r.08_09_0a_0b_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b
il128_constant_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b_08_09_0a_0b:
    .byte	0x08, 0x09, 0x0a, 0x0b, 0x08, 0x09, 0x0a, 0x0b, 0x08, 0x09, 0x0a, 0x0b, 0x08, 0x09, 0x0a, 0x0b

    .section .gnu.linkonce.r.04_05_06_07_14_15_16_17_0c_0d_0e_0f_1c_1d_1e_1f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_04_05_06_07_14_15_16_17_0c_0d_0e_0f_1c_1d_1e_1f
il128_constant_04_05_06_07_14_15_16_17_0c_0d_0e_0f_1c_1d_1e_1f:
    .byte	0x04, 0x05, 0x06, 0x07, 0x14, 0x15, 0x16, 0x17, 0x0c, 0x0d, 0x0e, 0x0f, 0x1c, 0x1d, 0x1e, 0x1f

    .section .gnu.linkonce.r.04_05_06_07_14_15_16_17_00_01_02_03_10_11_12_13,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_04_05_06_07_14_15_16_17_00_01_02_03_10_11_12_13
il128_constant_04_05_06_07_14_15_16_17_00_01_02_03_10_11_12_13:
    .byte	0x04, 0x05, 0x06, 0x07, 0x14, 0x15, 0x16, 0x17, 0x00, 0x01, 0x02, 0x03, 0x10, 0x11, 0x12, 0x13

    .section .gnu.linkonce.r.04_05_06_07_08_09_0a_0b_0c_0d_0e_0f_0c_0d_0e_0f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_04_05_06_07_08_09_0a_0b_0c_0d_0e_0f_0c_0d_0e_0f
il128_constant_04_05_06_07_08_09_0a_0b_0c_0d_0e_0f_0c_0d_0e_0f:
    .byte	0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x0c, 0x0d, 0x0e, 0x0f

    .section .gnu.linkonce.r.04_05_06_07_04_05_06_07_04_05_06_07_04_05_06_07,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_04_05_06_07_04_05_06_07_04_05_06_07_04_05_06_07
il128_constant_04_05_06_07_04_05_06_07_04_05_06_07_04_05_06_07:
    .byte	0x04, 0x05, 0x06, 0x07, 0x04, 0x05, 0x06, 0x07, 0x04, 0x05, 0x06, 0x07, 0x04, 0x05, 0x06, 0x07

    .section .gnu.linkonce.r.00_01_12_13_04_05_16_17_08_09_1a_1b_0c_0d_1e_1f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_12_13_04_05_16_17_08_09_1a_1b_0c_0d_1e_1f
il128_constant_00_01_12_13_04_05_16_17_08_09_1a_1b_0c_0d_1e_1f:
    .byte	0x00, 0x01, 0x12, 0x13, 0x04, 0x05, 0x16, 0x17, 0x08, 0x09, 0x1a, 0x1b, 0x0c, 0x0d, 0x1e, 0x1f

    .section .gnu.linkonce.r.00_01_02_03_10_11_12_13_08_09_0a_0b_18_19_1a_1b,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_10_11_12_13_08_09_0a_0b_18_19_1a_1b
il128_constant_00_01_02_03_10_11_12_13_08_09_0a_0b_18_19_1a_1b:
    .byte	0x00, 0x01, 0x02, 0x03, 0x10, 0x11, 0x12, 0x13, 0x08, 0x09, 0x0a, 0x0b, 0x18, 0x19, 0x1a, 0x1b

    .section .gnu.linkonce.r.00_01_02_03_10_11_12_13_04_05_06_07_14_15_16_17,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_10_11_12_13_04_05_06_07_14_15_16_17
il128_constant_00_01_02_03_10_11_12_13_04_05_06_07_14_15_16_17:
    .byte	0x00, 0x01, 0x02, 0x03, 0x10, 0x11, 0x12, 0x13, 0x04, 0x05, 0x06, 0x07, 0x14, 0x15, 0x16, 0x17

    .section .gnu.linkonce.r.00_01_02_03_04_05_06_07_18_19_1a_1b_1c_1d_1e_1f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_04_05_06_07_18_19_1a_1b_1c_1d_1e_1f
il128_constant_00_01_02_03_04_05_06_07_18_19_1a_1b_1c_1d_1e_1f:
    .byte	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f

    .section .gnu.linkonce.r.00_01_02_03_04_05_06_07_13_80_80_80_0c_0d_0e_0f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_04_05_06_07_13_80_80_80_0c_0d_0e_0f
il128_constant_00_01_02_03_04_05_06_07_13_80_80_80_0c_0d_0e_0f:
    .byte	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x13, 0x80, 0x80, 0x80, 0x0c, 0x0d, 0x0e, 0x0f

    .section .gnu.linkonce.r.00_01_02_03_04_05_06_07_10_11_12_13_80_80_80_80,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_04_05_06_07_10_11_12_13_80_80_80_80
il128_constant_00_01_02_03_04_05_06_07_10_11_12_13_80_80_80_80:
    .byte	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x10, 0x11, 0x12, 0x13, 0x80, 0x80, 0x80, 0x80

    .section .gnu.linkonce.r.00_01_02_03_04_05_06_07_08_09_0a_0b_0c_0d_0e_0f,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_04_05_06_07_08_09_0a_0b_0c_0d_0e_0f
il128_constant_00_01_02_03_04_05_06_07_08_09_0a_0b_0c_0d_0e_0f:
    .byte	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f

    .section .gnu.linkonce.r.00_01_02_03_00_01_02_03_00_01_02_03_00_01_02_03,"a"
    .align 4 # overall alignment for this section


    .align 4
    .global il128_constant_00_01_02_03_00_01_02_03_00_01_02_03_00_01_02_03
il128_constant_00_01_02_03_00_01_02_03_00_01_02_03_00_01_02_03:
    .byte	0x00, 0x01, 0x02, 0x03, 0x00, 0x01, 0x02, 0x03, 0x00, 0x01, 0x02, 0x03, 0x00, 0x01, 0x02, 0x03
