// 
// pheffects/tune.h 
// 
// Copyright (C) 1999-2013 Rockstar Games.  All Rights Reserved. 
// 

#ifndef PHEFFECTS_TUNE_H
#define PHEFFECTS_TUNE_H


namespace rage {

#define DEFAULT_VERLET_ITERS				3
#define DEFAULT_VERLET_ITERS_W_COLLISION	5
#define DEFAULT_ROPE_ITERATIONS				3
#define DEFAULT_COLLISION_PERIOD			1
#define DEFAULT_BEND_PERIOD					2
#define DEFAULT_CUSTOM_PERIOD				-1
#define DEFAULT_VERLET_DAMPING				0.05f
#define DEFAULT_BODY_MOVE_DAMPING			0.85f
#define DEFAULT_BODY_MOVE_ACCEL_FACTOR		0.1f

// all these numbers depend on MAX_VERLET_ITERS
#define DEFAULT_VERLET_COMPRESSION_STIFFNESS		0.25f 
#define DEFAULT_VERLET_FRICTION_MU					0.65f
#define DEFAULT_VERLET_STATIC_CLING					0.00125f
#define DEFAULT_VERLET_VERTEX_RADIUS				0.02f
#define DEFAULT_VERLET_COLLISION_MASS				0.01f
#define DEFAULT_VERLET_PINNING_SCALE				1.0f
#define DEFAULT_VERLET_LINEAR_DEFORMATION_DAMPING   0.5f
#define DEFAULT_VERLET_OVERRELAXATION_CONSTANT		1.55f
#define DEFAULT_VERLET_BENDSPRING_STIFFNESS			0.7f
#define DEFAULT_VERLET_BENDSPRING_LENGTH_SCALE		1.0f
#define DEFAULT_VERLET_GRAVITY_FACTOR				1.0f
#define DEFAULT_VERLET_PINNING_RADIUS_SCALE			1.0f



} // namespace rage

#endif // #ifndef PHEFFECTS_TUNE_H
